# name: Terraform Google Cloud Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Google Cloud CLI
#         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#         with:
#           version: '343.0.0'
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Install Google Cloud CLI
#         run: |
#           # Install the Google Cloud SDK
#           curl -sSL https://sdk.cloud.google.com | bash
#           exec -l $SHELL

#           # Authenticate with the service account
#           gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

#           # Update gcloud components
#           gcloud components update

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.8

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       - name: Terraform Apply
#         run: terraform apply -auto-approve tfplan
